# Generated by Django 2.1.1 on 2019-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_orderdetail_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.IntegerField(default=1, verbose_name='订单状态'),
        ),
    ]
