# Generated by Django 2.1.1 on 2019-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=1, verbose_name='订单状态'),
        ),
    ]
