# Generated by Django 2.1.1 on 2019-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
    ]
