# Generated by Django 2.1.1 on 2019-07-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190723_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_description',
            field=models.CharField(max_length=32, verbose_name='商品描述'),
        ),
    ]
